### ISSUE TITLE
Convert "New Paste" Navigation Bar Item to Button

### ISSUE THREAD

**Issue by daknob** [DaKnOb/TorPaste#17]
In previous versions of TorPaste (pre commit 7f96030b0ed33f76b29adde75b6751c7ec1b76be) the Navigation Bar button `[+] New Paste` was an actual button (`btn btn-primary`). After the mobile enhancements introduced in the commit above, that is no longer the case.

This decision was not taken lightly: the button simply did not look good no matter what. Since making TorPaste a mobile-friendly web app was of higher priority, the button has been downgraded to a simple tab / link / ...

Of course, we want the button back in to the project. Let's find a way to make the button usable without any hacks (`margin-top: -10px`) and have it look good in both Desktop and Mobile.

**Comment by vijeth-aradhya** [comment]
@DaKnOb I would like to work on this issue. Can you please assign it to me?

**Comment by daknob** [comment]
@vijeth-aradhya Of course! Good to know you're willing to help! I couldn't easily fix this myself, so I could need some help.. :-)

Feel free to fork and create a new PR.. If you're going to use more than once commit, you can open the PR and mark it as [WIP] so I can review the code while you work on it.
