### ISSUE TITLE
Add Option in Config File to Disable List

### ISSUE THREAD

**Issue by daknob** [DaKnOb/TorPaste#21]
Some TorPaste operators may not want the "Pastes" button / List feature to work for a various number of reasons. Let's add a configuration file option to disable that feature altogether.

**Comment by j11e** [comment]
Linked to #10 
(I add this to see the notification in the "main" ticket)

**Comment by j11e** [comment]
I'll take care of this one.

**Comment by daknob** [comment]
Great. Waiting for the PR.

**Comment by j11e** [comment]
As for the Python3 port, I'll hold on to the PR until #39 is successfully merged, so that I can fix potential conflicts.

**Comment by j11e** [comment]
FYI: I just have to fix the conflicts due to the PEP8 refactoring, then I'll be sending the PR.
