### ISSUE TITLE
Fix "Pastes" view on Mobile

### ISSUE THREAD

**Issue by daknob** [DaKnOb/TorPaste#30]
When viewing "Pastes" from a mobile phone, it looks something like this:

![pastes-mobile](https://cloud.githubusercontent.com/assets/743648/18989930/762395c2-8717-11e6-86a0-6539818a209a.png)

This is a bug that needs to be addressed. Let's see if text splitting is possible or some other way of showing them is better.

**Comment by vijeth-aradhya** [comment]
@DaKnOb Hi again! I would love to work on this issue. I will submit a PR in some time.

**Comment by daknob** [comment]
Sure, go ahead. I am not aware of any other people working on it, so it would be awesome. Plus, since today is October the 1st, this Pull Request will count towards Hacktoberfest!
