### ISSUE TITLE
TorPaste and iOS

### ISSUE THREAD

**Issue by daknob** [DaKnOb/TorPaste#31]
I do not know about other mobile operation systems, but in iOS, when visiting the page (say [this](https://paste.daknob.net/) the website shown is the full version and not the mobile one. I think this is done because iOS needs some special `<meta>` tags for the viewport. Can someone more experienced have a look and address this issue?

**Comment by vijeth-aradhya** [comment]
@DaKnOb As per my understanding, you _need_ to put `<meta>` tag to get a responsive design ( to view the web page on a phone in _any_ browser, not only Safari right? )

**Comment by daknob** [comment]
@vijeth-aradhya That's possible. Can you have a look into it? Looks like it will be something easy for you.. :-)
