### ISSUE TITLE
Switch TorPaste to Python3

### ISSUE THREAD

**Issue by j11e** [DaKnOb/TorPaste#32]
Switch TorPaste from Python2.7 to Python3. 

This simplifies many things such as UTF-8 handling, and ensures that future development will go more smoothly, as Python2.7 is slowly becoming a thing of the past (see [http://legacy.python.org/dev/peps/pep-0373/](http://legacy.python.org/dev/peps/pep-0373/) for the deprecation/end of life schedule).

This enhancement is developped in parallel in this repo and in [https://github.com/j11e/TorPaste](https://github.com/j11e/TorPaste) in the branch `python3`. Since this branch won't be merged in `master` before it is done and working, pull requests can be issued before the whole feature is done. However, if you want to contribute, please make sure that you are not duplicating your effort with something being done in the other repo, and make sure that TorPaste still runs before submitting a pull request.

**Comment by daknob** [comment]
100% Agreed. Make sure TorPaste is working and then submit Pull Requests to either `DaKnOb/TorPaste` (here) or `j11e/TorPaste`. For effort deduplication, you can submit a Pull Request and add `[WIP]` in front of the title so it won't be merged to `DaKnOb/TorPaste:python3`.

**Comment by j11e** [comment]
My fork is now working on Python3. Creating pastes, listing, and displaying them seem to work fine. I'll do some more thorough testing before submitting a pull request.

**Comment by daknob** [comment]
@j11e That's great news. I'll be checking it later to verify it works indeed. Can't wait for the PR.

**Comment by j11e** [comment]
Okay, my branch is stable, working both with a "naked" python3 install or with Docker, and ready for me to send a pull request.

I'll just wait for a decision on PR #39 so that I can rebase my `python3` branch on `master`  to make sure there will be no merge conflict. :)

**Comment by j11e** [comment]
I guess this is fixed now.
