### ISSUE TITLE
Fix issue with Tor Logo and website resizing

### ISSUE THREAD

**Issue by daknob** [DaKnOb/TorPaste#7]
Currently there's a weird issue where the Tor logo can be larger than the navbar in large screens. Let's work on addressing this issue.

**Comment by daknob** [comment]
This can be extended and clean up `style.css`.

**Comment by daknob** [comment]
Apparently this issue only appears in Mac OS X Safari and only when in Full Screen Mode. Let's see if we can get this fixed this time for good.

**Comment by vijeth-aradhya** [comment]
@DaKnOb Is there any other way to reproduce this bug other than in Mac OS X Safari?

**Comment by unkrich** [comment]
First pull request as part of Hacktoberfest - hopefully all is correct, but I believe I have resolved the issue in my referenced request above.

**Comment by daknob** [comment]
Fixed with Pull Request #27 and Commit 523153d
